### ISSUE TITLE
Help with Leaflet

### ISSUE THREAD

**Issue by carrbrpoa** [jsreport/jsreport-phantom-image#2]
Hello,

I'm trying to output image from HTML with LeafletJS. Done in playground: https://playground.jsreport.net/studio/workspace/Sk2SErnZz/7

But when trying to do it in my node server, it goes until timeout.
Code:

```
var jsreport = require('jsreport-core')({ tasks: { allowedModules: '*' } });
jsreport.use(require('jsreport-phantom-image')({ strategy: 'phantom-server' }));
...
app.get('/printmap', function (req, res, next) {
	jsreport.init().then(function () {
		return jsreport.render({
			template: {
				content: fs.readFileSync(path.join(__dirname, 'lib', 'index.html'), 'utf8'),
				engine: 'none',
				recipe: 'phantom-image',
				phantomImage: {
					waitForJS: true
				}
			}
		}).then(function (resp) {
			resp.result.on('end', function () {
				console.log('terminou');
			});
			resp.result.pipe(fs.createWriteStream('teste.png'));
		});
	}).catch (function (e) {
		console.log(e)
	})
});
```

The `index.html` referred there is the same "template" that is seen in playground.

Any ideas?

Thanks!

**Comment by bjrmatos** [comment]
hi! are you sure that you don't have more code that it is somehow getting into conflicts with jsreport?

i've just tried your example on my local machine (OSX with node 8.8.1) with the html of your playground and it worked for me as expected.

```js
// server.js
var path = require('path')
var fs = require('fs')
var jsreport = require('jsreport-core')({ tasks: { allowedModules: '*' } })

jsreport.use(require('jsreport-phantom-image')({ strategy: 'phantom-server' }))

jsreport.init().then(function () {
  console.log('jsreport initialized')

  return jsreport.render({
    template: {
      content: fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8'),
      engine: 'none',
      recipe: 'phantom-image',
      phantomImage: {
        waitForJS: true
      }
    }
  }).then(function (resp) {
    console.log('rendering finished, writing content to file..')

    resp.result.on('end', function () {
      console.log('terminou');
    });
    resp.result.pipe(fs.createWriteStream('teste.png'));
  });
}).catch(function (e) {
  // error during startup
  console.error(e.stack)
  process.exit(1)
})

```

```html
<!-- index.html -->
<html>
<head>
    <title>Mobile tutorial - Leaflet</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.js"></script>

    <style>
        html,
        body {
            height: 250px;
            margin: 0;
            padding: 0;
        }

        #map {
            height: 100%;
            width: 375px;
        }
    </style>
</head>

<body>
    <h1>Oi</h1>
    <div id='map'></div>
    <script>
        window.map = L.map('map',
			{
				zoomControl: false
			}
		);

		/*window.map.on('load', function () {
            console.log('LOAD');
            window.JSREPORT_READY_TO_START = true;
        });

		window.map.on('moveend', function () {
			console.log('MOVEEND');
        });

		window.map.on('layeradd', function () {
            console.log('LAYERADD');
            window.JSREPORT_READY_TO_START = true;
        });*/

		window.onload = function() {
            console.log('ONLOAD');
            window.JSREPORT_READY_TO_START = true;
		};

		L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
            maxZoom: 20,
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
            '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
            'Imagery © <a href="http://mapbox.com">Mapbox</a>',
            id: 'mapbox.streets'
        }).addTo(map);

		var center = new L.LatLng(-30.036835, -51.216092);
		map.setView(center, 18);

        /*map.on('load', function () {
            window.JSREPORT_READY_TO_START = true;
        });*/
    </script>
</body>

</html>

```

it produced the following image:

![teste](https://user-images.githubusercontent.com/4262050/33862250-c811c322-deaf-11e7-839b-873d95ff1184.png)

**Comment by carrbrpoa** [comment]
Hi! Thanks for the response. I'm not with the code right now but I don't
think so. I remember of a suspicious concerning proxy, since the machine
I'm running that code is behind an enterprise proxy. There is any extra
configuration I should do, considering that? Otherwise, I'll take a closer
look at code tomorrow. Thanks a lot!

**Comment by carrbrpoa** [comment]
The output:

```
  jsreport info Initializing jsreport@1.5.1 in development mode +0ms
  jsreport info Setting process based strategy for rendering. Please visit http://jsreport.net/learn/configuration for information how to get more performance.
+2ms
  jsreport info Using extension phantom-image +4ms
  jsreport info Creating memory store +34ms
  jsreport info reporter initialized +12ms
  jsreport info Starting rendering request 1 (user: null) +1ms
  jsreport debug Rendering engine none +2ms
  jsreport debug Compiled template not found in the cache, compiling +142ms
  jsreport debug Executing recipe phantom-image +2ms
  jsreport debug Pdf recipe start. +1ms
  jsreport warn Error when processing render request Error during rendering report: Timeout Error: Timeout
  jsreport     at C:\eclipse-mars\workspace\osdcvu-app-api\node_modules\phantom-workers\lib\phantomManager.js:112:29
  jsreport     at C:\eclipse-mars\workspace\osdcvu-app-api\node_modules\phantom-workers\lib\phantomWorker.js:111:20
  jsreport     at Socket.<anonymous> (C:\eclipse-mars\workspace\osdcvu-app-api\node_modules\phantom-workers\lib\checkPortStatus.js:45:9)
  jsreport     at emitOne (events.js:115:13)
  jsreport     at Socket.emit (events.js:210:7)
  jsreport     at TCP._handle.close [as _onclose] (net.js:546:12) +3m
{ Error: Timeout
    at C:\eclipse-mars\workspace\osdcvu-app-api\node_modules\phantom-workers\lib\phantomManager.js:112:29
    at C:\eclipse-mars\workspace\osdcvu-app-api\node_modules\phantom-workers\lib\phantomWorker.js:111:20
    at Socket.<anonymous> (C:\eclipse-mars\workspace\osdcvu-app-api\node_modules\phantom-workers\lib\checkPortStatus.js:45:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:546:12)
  weak: true,
  message: 'Error during rendering report: Timeout',
  phantomTimeout: true }
```

**Comment by bjrmatos** [comment]
closing the issue since this is likely not a jsreport issue and more about proxy configuration with phantomjs and proxy rules in user's network. 

if you have more things to add to the conversation feel free to continue adding comments.
