### ISSUE TITLE
Is this no longer working?

### ISSUE THREAD

**Issue by Warriormuffin** [jsreport/jsreport-phantom-image#3]
I just get recipe ''phantom-image" not found.

**Comment by bjrmatos** [comment]
yes, it works. i have tried it recently with the following steps:

- npm i -g jsreport-cli (if you don't have the jsreport cli already installed)
- create a new folder and the open a command line at that folder and run `jsreport init` (wait until it finish)
- npm i jsreport-phantom-image --save
- jsreport start
- open jsreport studio at localhost:5488, create a new template and use the phantom-image recipe

finally it worked as expected, how are you installing and using it?

**Comment by Warriormuffin** [comment]
I will try this method this morning and let you know if it works

**Comment by Warriormuffin** [comment]
I seem to have gotten pass the issue of the recipe not being defined but now i run into this.

Error occured - Error during rendering report: Command failed: /Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/q6/c5t4269j06s9blllckjkh00c0000gp/T/jsreport/6949c240-1e3d-11e8-a9c7-33b1049251aasettings.html

**Comment by Warriormuffin** [comment]
It seems to be an issue just with the jsreport-image recipe since other recipes do not produce the same error. I followed your above steps

**Comment by bjrmatos** [comment]
what os are you using? OSX? is there no other error in console?

**Comment by Warriormuffin** [comment]
I am running OSX High Sierra. That is the only error that is produced. 
![screen shot 2018-03-02 at 12 44 59 pm](https://user-images.githubusercontent.com/19913775/36918575-93c09bbe-1e17-11e8-8e14-316684310fd1.png)

**Comment by bjrmatos** [comment]
i see, this package installs phantom 1.9.8 and such version of phantomjs does not work on OSX Sierra, we have some notes about that [here](https://jsreport.net/learn/phantom-pdf#macos-sierra). 

the solution is that you need to use phantomjs 2, you should be able to install the executable by yourself and then in your configuration file `jsreport.config.json` file add the following:

```js
{
   ...
   "phantom-image": {
     "phantomPath": "/path/to/the/phantomjs2executable"
   }
   ...
}
```

that should be make `jsreport-phantom-image` to use phantomjs2 and work in your machine

**Comment by Warriormuffin** [comment]
`{
  "certificate": {
    "key": "certificates/jsreport.net.key",
    "cert": "certificates/jsreport.net.cert"
  },
  "authentication": {
    "cookieSession": {
      "secret": "<your strong secret>"
    },
    "admin": {
      "username": "admin",
      "password": "password"
    },
    "enabled": false
  },
  "connectionString": {
    "name": "fs"
  },
  "httpPort": 5488,
  "httpsPort": null,
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },
  "blobStorage": "fileSystem",
  "phantom": {
    "strategy": "dedicated-process",
    "timeout": 60000
    },
    "phantom-image": {
     "phantomPath": "/path/to/the/phantomjs2executable"
   },
  "tasks": {
    "strategy": "dedicated-process",
    "timeout": 10000,
    "allowedModules": []
  },
  "scripts": {
    "allowedModules": [],
    "timeout": 60000
  },
  "sample-template": {
    "createSamples": true
  }
}
`

That is my config file but I am still running into the same issue. I was able to fix this issue with the PDF by just specifying version in the request object

**Comment by bjrmatos** [comment]
just to have it complete it clear and to ensure that there is no mistake here:

```
"phantom-image": {
    "phantomPath": "/path/to/the/phantomjs2executable"
  }
```

what is the real path in your system that you are using in this option? i just put `/path/to/the/phantomjs2executable` as a placeholder for you to replace with the real path on your system. have you changed it? or you just forgot about it?

**Comment by Warriormuffin** [comment]
Me being an idiot i forgot to change it out. 

"phantom": {
    "strategy": "dedicated-process",
    "defaultPhantomjsVersion": "2.1.1",
    "timeout": 60000
    },
    "phantom-image": {
     "phantomPath": "node_modules/phantomjs-exact-2-1-1"
   },

I might have done something wrong but i get to a point and then jsreports server crashes on my computer 

`2018-03-05T17:19:44.941Z - debug: Rendering engine jsrender requestId=1
2018-03-05T17:19:45.336Z - debug: Compiled template not found in the cache, compiling timestamp=Mon Mar 05 2018 10:19:45 GMT-0700 (MST), requestId=1
2018-03-05T17:19:45.338Z - debug: Replaced images [] requestId=1
2018-03-05T17:19:45.340Z - debug: Executing recipe phantom-image requestId=1
2018-03-05T17:19:45.340Z - debug: Pdf recipe start. requestId=1
`

Maybe i am linking to the wrong file?

**Comment by bjrmatos** [comment]
that is not the full path to the phantom 2 executable, for example on my osx machine the full path is this `/Volumes/DATA/workspace/jsreport-test/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs`, it should be something similar for you too, just be sure to replace `/Volumes/DATA/workspace/jsreport-test/` with the full path to your project directory and to check the the binary is there

**Comment by Warriormuffin** [comment]
Trying a couple other paths but what i believe is the correct path threw this error

`Error occured - Error during rendering report: spawn /source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs ENOENT`

Thanks for helping me btw!

**Comment by bjrmatos** [comment]
what happens if you execute `/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs --version`? it should print `2.1.1`.

**Comment by Warriormuffin** [comment]
Weird i just get no such file or directory even though i can see that the node module is in my project. It must be me messing up the path somehow

**Comment by bjrmatos** [comment]
can you put here the output of the following command?

`ls -al /source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules`

**Comment by Warriormuffin** [comment]
ls: /source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules: No such file or directory

**Comment by Warriormuffin** [comment]
but running .//source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs --version               
got me
2.1.1

**Comment by bjrmatos** [comment]
do you mean this command `.//source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs --version` gave you that output? weird, if that is the case try to put that path in jsreport config and try again

**Comment by bjrmatos** [comment]
just to be clear, just this in config `.//source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs`

**Comment by Warriormuffin** [comment]
trying now

**Comment by Warriormuffin** [comment]
With .// i got

`2018-03-05T18:23:35.433Z - error: Error during processing request: http://localhost:5488/api/report/gpoproofvertical details: Error during rendering report: Command failed: .//source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/q6/c5t4269j06s9blllckjkh00c0000gp/T/jsreport/51374e90-20a2-11e8-90e2-7771f334f29csettings.html
env: node: No such file or directory`

trying with just ./source

EDIT: Same thing when running 

`./source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs`

**Comment by bjrmatos** [comment]
i think something is wrong here and we are not getting your real full path. according to your logs your real full path is `/Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs`, can you put that in jsreport config and try again?

**Comment by Warriormuffin** [comment]
Sorry I got wrapped up in a meeting at work. 

I tried that and i get 

` Error occured - Error during rendering report: Command failed: /Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/q6/c5t4269j06s9blllckjkh00c0000gp/T/jsreport/a5b3cdb0-20af-11e8-a74f-f9982520e0e8settings.html
env: node: No such file or directory

Stak - Error: Command failed: /Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/q6/c5t4269j06s9blllckjkh00c0000gp/T/jsreport/a5b3cdb0-20af-11e8-a74f-f9982520e0e8settings.html
env: node: No such file or directory

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)`

**Comment by bjrmatos** [comment]
just figured out that the correct path is another location (i have checked my own machine): please try with `/Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs` in config.

**Comment by Warriormuffin** [comment]
testing now

**Comment by Warriormuffin** [comment]
That gave me 

`error: Error during processing request: http://localhost:5488/api/report/gpoproofvertical details: Error during rendering report: spawn /Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT Error: spawn /Users/nathanelg/source/CP3-GPO/Freeman.CP3.Web/node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

inside my lib/ there is only location.js/phantomjs.js/util.js no phantom folder

**Comment by bjrmatos** [comment]
what is the content of `cat node_modules/phantomjs-exact-2-1-1/node_modules/phantomjs-prebuilt/lib/location.js`?

for me is this: 

```js
module.exports.location = "phantom/bin/phantomjs"
module.exports.platform = "darwin"
module.exports.arch = "x64"
```

**Comment by Warriormuffin** [comment]
module.exports.location = "/usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs"
module.exports.platform = "darwin"
module.exports.arch = "x64"

**Comment by bjrmatos** [comment]
does the output of `/usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --version` is still `2.1.1`? if yes, then use that path in your jsreport config `/usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs`.

**Comment by Warriormuffin** [comment]
I still need to test this out but i moved everything into a docker container so not sure if the phatom-image stuff will work through a docker container?

**Comment by bjrmatos** [comment]
yes, in docker (linux), phantom 1.9.8 will work, but you will probably need to install some things additionally depending on the linux distribution that you are going to use, you can find some info [here](https://github.com/jsreport/docs/blob/master/installation/ubuntu.md#fixing-phantomjs) and [here](https://github.com/jsreport/docs/blob/master/installation/centos.md#fixing-pdf-fonts). 

you can also use our [full docker image](https://github.com/jsreport/jsreport/tree/master/docker/full) that comes with `jsreport-phantom-image`

**Comment by Warriormuffin** [comment]
We are using the full docker image so nice to know it comes with phantom-image! Does phantom 2.1.1 work within the docker container? It doesnt seem to come with the phantomjs 2.1.1 out of the box. If we wanted we could just npm install phantomjs-exact-2-1-1 correct?

**Comment by bjrmatos** [comment]
> It doesnt seem to come with the phantomjs 2.1.1 out of the box.

[the full comes with phantom 2.1.1 too](https://github.com/jsreport/jsreport/blob/master/docker/full/Dockerfile#L65)

**Comment by Warriormuffin** [comment]
https://hub.docker.com/r/jsreport/jsreport/ 

Is the one you linked and the one I linked the same? So many different versions 😄

**Comment by Warriormuffin** [comment]
sudo docker run -e "phantom_strategy=dedicated-process" -e "phantom_defaultPhantomjsVersion=2.1.1"  jsreport/jsreport         Running that just throws the errror 

error: Error when loading extension Error: defaultPhantomjsVersion 2.1.1 was not found
Error: defaultPhantomjsVersion 2.1.1 was not found.

I am guessing we are running the wrong docker container.

**Comment by bjrmatos** [comment]
the full docker tag is `jsreport/jsreport:1.10.0-full`, your command should be: `sudo docker run -e "phantom_strategy=dedicated-process" -e "phantom_defaultPhantomjsVersion=2.1.1" jsreport/jsreport:1.10.0-full`

**Comment by Warriormuffin** [comment]
I know i have a ton of questions and you have been a ton of help.

This is what docker spits out.

```
`Trying to remove the lock on display 99
Running display 99
Starting node.js
2018-03-07T20:12:16.649Z - info: Initializing jsreport@1.10.0 in production mode using configuration file: jsreport.config.json
2018-03-07T20:12:16.829Z - info: Searching for available extensions in /usr/src/app/
2018-03-07T20:12:16.831Z - info: Extensions location cache not found, crawling directories
2018-03-07T20:12:17.094Z - info: Found 43 extensions
2018-03-07T20:12:17.117Z - debug: Writing extension locations cache to /tmp/jsreport/core/locations.json
2018-03-07T20:12:17.118Z - debug: Discovered 43 extensions
2018-03-07T20:12:17.120Z - info: Using extension jsrender
2018-03-07T20:12:17.122Z - info: Using extension test
2018-03-07T20:12:17.123Z - info: Using extension templates
2018-03-07T20:12:17.127Z - info: Using extension tags
2018-03-07T20:12:17.133Z - info: Using extension postgres-store
2018-03-07T20:12:17.315Z - info: Using extension mssql-store
2018-03-07T20:12:17.327Z - info: Using extension mongodb-store
2018-03-07T20:12:17.414Z - info: Using extension cli
2018-03-07T20:12:17.415Z - debug: Extension authentication is disabled, skipping
2018-03-07T20:12:17.415Z - info: Using extension debug
2018-03-07T20:12:17.416Z - info: Using extension ejs
2018-03-07T20:12:17.417Z - info: Using extension jade
2018-03-07T20:12:17.419Z - info: Using extension express
2018-03-07T20:12:17.547Z - info: Using extension fop-pdf
2018-03-07T20:12:17.601Z - info: Using extension freeze
2018-03-07T20:12:17.602Z - info: Using extension import-export
2018-03-07T20:12:17.788Z - info: Using extension handlebars
2018-03-07T20:12:17.789Z - info: Using extension reports
2018-03-07T20:12:17.833Z - info: Using extension html-to-xlsx
2018-03-07T20:12:17.940Z - info: Using extension fs-store
2018-03-07T20:12:18.190Z - info: synchronization of changes in jsreport-fs-store are disabled
2018-03-07T20:12:18.191Z - info: Using extension electron-pdf
2018-03-07T20:12:18.278Z - info: Using extension data
2018-03-07T20:12:18.318Z - info: Using extension licensing
2018-03-07T20:12:18.417Z - info: Using extension chrome-pdf
2018-03-07T20:12:18.464Z - info: Using extension child-templates
2018-03-07T20:12:18.468Z - info: Using extension pdf-utils
2018-03-07T20:12:18.659Z - info: Using extension phantom-image
2018-03-07T20:12:18.665Z - info: Using extension phantom-pdf
2018-03-07T20:12:18.790Z - info: Using extension browser-client
2018-03-07T20:12:18.792Z - info: Using extension wkhtmltopdf
2018-03-07T20:12:18.846Z - info: Using extension images
2018-03-07T20:12:18.887Z - info: Using extension resources
2018-03-07T20:12:18.926Z - info: Using extension version-control
2018-03-07T20:12:18.944Z - info: Using extension text
2018-03-07T20:12:18.945Z - info: Using extension authorization
2018-03-07T20:12:18.972Z - debug: Extension authorization was disabled
2018-03-07T20:12:18.972Z - info: Using extension studio
2018-03-07T20:12:19.033Z - info: Using extension base
2018-03-07T20:12:19.034Z - info: Using extension scripts
2018-03-07T20:12:19.073Z - info: Using extension scheduling
2018-03-07T20:12:19.098Z - info: Using extension xlsx
2018-03-07T20:12:19.281Z - info: Using extension assets
2018-03-07T20:12:19.285Z - info: Using extension sample-template
2018-03-07T20:12:19.325Z - info: Using extension public-templates
2018-03-07T20:12:19.367Z - debug: Extension public-templates was disabled
2018-03-07T20:12:19.371Z - info: Initializing fs storage at /usr/src/app/data
2018-03-07T20:12:19.455Z - info: Creating default express app.
2018-03-07T20:12:19.520Z - debug: Inserting samples
2018-03-07T20:12:19.513Z - info: jsreport server successfully started on http port: 5488
2018-03-07T20:12:19.515Z - info: Verifying license key free
2018-03-07T20:12:19.516Z - info: Using free license
2018-03-07T20:12:19.533Z - debug: Inserting sample entity Population
2018-03-07T20:12:19.533Z - debug: Inserting sample entity Invoice
2018-03-07T20:12:19.534Z - debug: Inserting sample entity Invoice logo.png
2018-03-07T20:12:19.534Z - debug: Inserting sample entity Orders
2018-03-07T20:12:19.534Z - debug: Inserting sample entity Population
2018-03-07T20:12:19.544Z - debug: Inserting sample entity Invoice
2018-03-07T20:12:19.544Z - debug: Inserting sample entity Population
2018-03-07T20:12:19.544Z - debug: Inserting sample entity global helpers.js
2018-03-07T20:12:19.555Z - debug: Inserting sample entity Orders
2018-03-07T20:12:19.555Z - debug: Inserting sample entity Invoice styles.css
2018-03-07T20:12:19.638Z - info: reporter initialized`
```


We do not have access to pahntomjsVerison 2.1.1 still for some reason

Plus on the actual server, I can see the anonymous report being generating with 

+37 | Executing recipe phantom-pdf
-- | --
+68 | Converting in http server based phantomjs 1.9.8


which is super weird since I set 
phantom: {
                    phantomjsVersion: '2.1.1', margin: '0px', headerheight: '1in', format:
                        'letter', orientation: 'portrait'

**Comment by bjrmatos** [comment]
hmm can you please show what is the full json request that you are sending? i will try to find some time to try the full docker image in my machine.
